// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Sku         string    `json:"sku"`
	Price       float64   `json:"price"`
	CategoryID  string    `json:"categoryId"`
	Category    *Category `json:"category,omitempty"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
}

type Query struct {
}

type ProductSortBy string

const (
	ProductSortByPriceAsc      ProductSortBy = "PRICE_ASC"
	ProductSortByPriceDesc     ProductSortBy = "PRICE_DESC"
	ProductSortByCreatedAtAsc  ProductSortBy = "CREATED_AT_ASC"
	ProductSortByCreatedAtDesc ProductSortBy = "CREATED_AT_DESC"
)

var AllProductSortBy = []ProductSortBy{
	ProductSortByPriceAsc,
	ProductSortByPriceDesc,
	ProductSortByCreatedAtAsc,
	ProductSortByCreatedAtDesc,
}

func (e ProductSortBy) IsValid() bool {
	switch e {
	case ProductSortByPriceAsc, ProductSortByPriceDesc, ProductSortByCreatedAtAsc, ProductSortByCreatedAtDesc:
		return true
	}
	return false
}

func (e ProductSortBy) String() string {
	return string(e)
}

func (e *ProductSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductSortBy", str)
	}
	return nil
}

func (e ProductSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
