package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Create category
func (r *mutationResolver) CreateCategory(ctx context.Context, name string) (*Category, error) {
	if name == "" {
		return nil, gqlerror.Errorf("name cannot be empty")
	}

	item, err := r.CategoryService.CreateCategory(name)
	if err != nil {
		return nil, err
	}

	return &Category{
		ID:   strconv.FormatUint(uint64(item.ID), 10),
		Name: item.Name,
	}, nil
}

// Create product
func (r *mutationResolver) CreateProduct(ctx context.Context, name string, description string, sku string, price float64, categoryID string) (*Product, error) {
	if name == "" {
		return nil, gqlerror.Errorf("name cannot be empty")
	}

	if sku == "" {
		return nil, gqlerror.Errorf("sku cannot be empty")
	}

	if price <= 0 {
		return nil, gqlerror.Errorf("price must be greater than 0")
	}

	parsedCategoryID, err := strconv.ParseUint(categoryID, 10, 64)
	if err != nil {
		return nil, gqlerror.Errorf("invalid category id")
	}

	item, err := r.ProductService.CreateProduct(
		name,
		description,
		sku,
		price,
		uint(parsedCategoryID),
	)
	if err != nil {
		return nil, err
	}

	return toGraphQLProduct(*item), nil
}

// Products list
func (r *queryResolver) Products(ctx context.Context, limit int, minPrice *float64, maxPrice *float64, categoryID *string) ([]*Product, error) {
	var parsedCategoryID *uint

	if categoryID != nil {
		id, err := strconv.ParseUint(*categoryID, 10, 64)
		if err != nil {
			return nil, gqlerror.Errorf("invalid category id")
		}
		value := uint(id)
		parsedCategoryID = &value
	}

	items, err := r.ProductService.GetProducts(limit, minPrice, maxPrice, parsedCategoryID)
	if err != nil {
		return nil, err
	}

	result := make([]*Product, 0, len(items))
	for _, item := range items {
		result = append(result, toGraphQLProduct(item))
	}

	return result, nil
}

// Single product
func (r *queryResolver) Product(ctx context.Context, id string) (*Product, error) {
	parsedID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, gqlerror.Errorf("invalid product id")
	}

	item, err := r.ProductService.GetProductByID(uint(parsedID))
	if err != nil {
		return nil, gqlerror.Errorf("product not found")
	}

	return toGraphQLProduct(*item), nil
}

// Categories list
func (r *queryResolver) Categories(ctx context.Context) ([]*Category, error) {
	items, err := r.CategoryService.GetCategories()
	if err != nil {
		return nil, err
	}

	result := make([]*Category, 0, len(items))
	for _, item := range items {
		result = append(result, &Category{
			ID:   strconv.FormatUint(uint64(item.ID), 10),
			Name: item.Name,
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
